
// selection event
const NEW_GAME = 'NEW_GAME';
const GAME_UPDATE = 'GAME_UPDATE';

// game event
const USER_JOIN_GAME = 'USER_JOIN_GAME';
const USER_POST_CHAT = 'USER_POST_CHAT';
const LAUCH_GAME = 'LAUCH_GAME';
const SWITCH_RUNNING_STATUS = 'SWITCH_RUNNING_STATUS';
const SEND_ANIME_TO_GUESS = 'SEND_ANIME_TO_GUESS';
const CLICK_ANSWER = 'CLICK_ANSWER';


module.exports = {
    NEW_GAME,
    GAME_UPDATE,
    USER_JOIN_GAME,
    USER_POST_CHAT,
    LAUCH_GAME,
    SWITCH_RUNNING_STATUS,
    SEND_ANIME_TO_GUESS,
    CLICK_ANSWER,
}

