
// selection event
const NEW_GAME = 'NEW_GAME';
const GAME_UPDATE = 'GAME_UPDATE';

// game event
const USER_JOIN_GAME = 'USER_JOIN_GAME';
const USER_POST_CHAT = 'USER_POST_CHAT';
const LAUCH_GAME = 'LAUCH_GAME';
//const CHANGE_RUNNING_STATUS = 'CHANGE_RUNNING_STATUS';
const SEND_ANIME_TO_GUESS = 'SEND_ANIME_TO_GUESS';
const CLICK_ANSWER = 'CLICK_ANSWER';

const CHANGE_STATUS_0_TO_1 = 'CHANGE_STATUS_0_TO_1';
const CHANGE_STATUS_1_TO_2 = 'CHANGE_STATUS_1_TO_2';
const CHANGE_STATUS_2_TO_0 = 'CHANGE_STATUS_2_TO_0';
const SET_DEFAULT_STATUS = 'SET_DEFAULT_STATUS';

module.exports = {
    NEW_GAME,
    GAME_UPDATE,
    USER_JOIN_GAME,
    USER_POST_CHAT,
    LAUCH_GAME,
    SEND_ANIME_TO_GUESS,
    CLICK_ANSWER,
    CHANGE_STATUS_0_TO_1,
    CHANGE_STATUS_1_TO_2,
    CHANGE_STATUS_2_TO_0,
    SET_DEFAULT_STATUS,
}

